In [26]:
import pandas as pd
import numpy as np
df = pd.read_csv('messy_customers.csv')
df.head()

          name   age      city    salary signup_date
0  Evan Wright  43.0   Houston  80357.89  2023-12-15
1  Julia Novak  32.0   houston  48010.94  2024-08-07
2  Julia Novak  64.0   Phoenix  85386.57  2024-01-27
3  Alice Smith   NaN   houston  54980.08  2023-09-08
4   George Kim  37.0  chicago   53019.63  2023-04-23

In [27]:
print(df.describe())
df.info()

             age         salary
count  38.000000      39.000000
mean   43.763158   78238.478205
std    15.415742  144258.604994
min    -5.000000   20858.740000
25%    33.000000   46864.120000
50%    46.500000   53862.790000
75%    55.000000   69521.425000
max    64.000000  950000.000000
<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         40 non-null     str
 1   age          38 non-null     float64
 2   city         40 non-null     str
 3   salary       39 non-null     float64
 4   signup_date  39 non-null     str
dtypes: float64(2), str(3)
memory usage: 1.2 KB

In [28]:
print(df[df.duplicated()])

           name   age     city    salary signup_date
15  Julia Novak  64.0  Phoenix  85386.57  2024-01-27

In [29]:
df['city'].unique()

<StringArray>
[    'Houston',     'houston',     'Phoenix',    'chicago ',    'Phoenix ',
          'LA', 'Los Angeles',     'Chicago',    'new york',    'New York']
Length: 10, dtype: str

In [30]:
df['name'].unique()

<StringArray>
[   'Evan Wright',    'Julia Novak',    'Alice Smith',     'George Kim',
   'Hannah Patel',       'Dana Lee',  'CHARLIE DAVIS',    'Ian Wallace',
     'Fiona Chen', 'Hannah Patel  ',      'bob jones']
Length: 11, dtype: str

In [31]:
#Remove duplicate column
df = df.drop_duplicates()
print(df[df.duplicated()])

Empty DataFrame
Columns: [name, age, city, salary, signup_date]
Index: []

In [32]:
#change negative age to NaN
df.loc[df['age']<0, 'age'] = np.nan
df.describe()

             age         salary
count  36.000000      38.000000
mean   44.555556   78050.370526
std    13.074390  146190.201407
min    18.000000   20858.740000
25%    33.000000   46335.630000
50%    46.500000   53441.210000
75%    53.000000   67991.342500
max    64.000000  950000.000000

In [33]:
#store median salary from full dataset
salary = df['salary'].median()

#drop rows with Null age or date
df = df.dropna(subset=['age', 'signup_date'])

#Replace Nan with median salary
df.loc[df['salary'].isna(), 'salary'] = salary

#Check all NaNs are removed
df.isna().sum()

name           0
age            0
city           0
salary         0
signup_date    0
dtype: int64

In [34]:
#Solve LA problem
df.loc[df['city'] == 'LA', 'city'] = 'Los Angeles'

#remove surrounding whitespace and case standardisation
df['city'] = df['city'].str.strip().str.title()

df['city'].unique()

<StringArray>
['Houston', 'Phoenix', 'Chicago', 'Los Angeles', 'New York']
Length: 5, dtype: str

In [36]:
#remove surrounding whitespace and case standardisation
df['name'] = df['name'].str.strip().str.title()

df['name'].unique()

<StringArray>
[  'Evan Wright',   'Julia Novak',    'George Kim',   'Alice Smith',
  'Hannah Patel',      'Dana Lee',   'Ian Wallace',    'Fiona Chen',
 'Charlie Davis',     'Bob Jones']
Length: 10, dtype: str

In [37]:
#sort Dtype of date
df['signup_date'] = pd.to_datetime(df['signup_date'])

df.info()

<class 'pandas.DataFrame'>
Index: 35 entries, 0 to 39
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         35 non-null     str
 1   age          35 non-null     float64
 2   city         35 non-null     str
 3   salary       35 non-null     float64
 4   signup_date  35 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 1.4 KB